<?php namespace Baruck; ?>
<?php if ($page === 'dashboard'): $counts = query("SELECT COUNT(*) AS total,COALESCE(SUM(status='draft'),0) AS drafts,(SELECT COUNT(*) FROM article_publications) AS ready FROM articles")->fetch(); ?>
    <section class="rounded-2xl bg-ink p-7 text-ivory tablet:p-9"><p class="text-xs uppercase tracking-[.18em] text-gold">Les contenus du Groupe</p><h2 class="mt-3 font-display text-3xl">Une actualité à partager ?</h2><p class="mt-3 max-w-xl text-sm leading-relaxed text-ivory/65">Commencez par un brouillon. Ajoutez vos images, relisez votre texte et faites-le valider avant la prochaine publication du site.</p><a href="<?= e(url('edit')) ?>" class="<?= $buttonClass ?> mt-6">Rédiger une actualité <span class="ml-4" aria-hidden="true">+</span></a></section>
    <div class="mt-7 grid gap-4 tablet:grid-cols-3"><?php foreach (['total' => 'Actualités', 'drafts' => 'Brouillons et révisions', 'ready' => 'Validées pour publication'] as $key => $label): ?><div class="rounded-xl border border-line bg-ivory p-6"><p class="text-sm text-ink/60"><?= $label ?></p><p class="mt-3 font-display text-4xl"><?= (int) $counts[$key] ?></p></div><?php endforeach; ?></div>
    <section class="mt-9"><div class="mb-4 flex items-center justify-between"><h2 class="font-display text-2xl">Dernières modifications</h2><a href="<?= e(url('articles')) ?>" class="text-sm underline underline-offset-4">Toutes les actualités</a></div><div class="divide-y divide-line rounded-xl border border-line bg-ivory"><?php foreach (query('SELECT a.id,a.title,a.status,a.updated_at,p.version AS publication_version FROM articles a LEFT JOIN article_publications p ON p.article_id=a.id ORDER BY a.updated_at DESC,a.title LIMIT 5')->fetchAll() as $row): ?><a href="<?= e(url('edit', ['id' => $row['id']])) ?>" class="flex flex-wrap items-center justify-between gap-3 p-5 hover:bg-paper-deep/30"><span class="text-sm font-semibold"><?= e($row['title']) ?></span><span class="rounded-full bg-paper px-3 py-1 text-xs"><?= ($row['publication_version'] !== null ? ($row['status'] === 'ready' ? 'Validé' : 'Révision en cours') : 'Brouillon') ?></span></a><?php endforeach; ?></div></section>
<?php elseif ($page === 'articles'): $search = is_string($_GET['q'] ?? null) ? substr($_GET['q'], 0, 120) : ''; $filter = in_array($_GET['status'] ?? '', ['draft', 'ready'], true) ? $_GET['status'] : ''; $rows = query('SELECT a.id,a.title,a.category,a.article_date,a.status,a.updated_at,p.version AS publication_version FROM articles a LEFT JOIN article_publications p ON p.article_id=a.id WHERE a.title LIKE ? AND (? = ? OR a.status = ?) ORDER BY a.updated_at DESC,a.title', ['%' . $search . '%', $filter, '', $filter])->fetchAll(); ?>
    <div class="mb-6 flex flex-wrap items-center justify-between gap-4"><p class="text-sm text-ink/60"><?= count($rows) ?> actualité(s)</p><a href="<?= e(url('edit')) ?>" class="<?= $buttonClass ?>">Nouvelle actualité <span class="ml-4" aria-hidden="true">+</span></a></div>
    <form method="get" class="mb-6 grid items-end gap-4 tablet:grid-cols-[1fr_220px_auto]"><input type="hidden" name="page" value="articles"><div><?php field('Rechercher un titre', 'q', $search, 'search'); ?></div><div><label for="status" class="text-sm font-medium">Statut</label><select id="status" name="status" class="<?= $inputClass ?>"><option value="">Tous les statuts</option><option value="draft" <?= $filter === 'draft' ? 'selected' : '' ?>>Brouillons et révisions</option><option value="ready" <?= $filter === 'ready' ? 'selected' : '' ?>>Validés</option></select></div><button class="<?= $secondaryClass ?>">Filtrer</button></form>
    <div class="overflow-x-auto rounded-xl border border-line bg-ivory"><table class="w-full text-left text-sm"><caption class="sr-only">Liste des actualités</caption><thead class="bg-paper-deep/35 text-xs text-ink/60"><tr><th scope="col" class="p-5">Titre</th><th scope="col" class="p-5">Catégorie</th><th scope="col" class="p-5">Date de l’actualité</th><th scope="col" class="p-5">Statut</th></tr></thead><tbody class="divide-y divide-line"><?php foreach ($rows as $row): ?><tr><th scope="row" class="p-5 font-semibold"><a class="underline-offset-4 hover:underline" href="<?= e(url('edit', ['id' => $row['id']])) ?>"><?= e($row['title']) ?></a></th><td class="p-5"><?= e(categories()[$row['category']]) ?></td><td class="whitespace-nowrap p-5"><?= e($row['article_date'] ?: 'À renseigner') ?></td><td class="p-5"><span class="whitespace-nowrap rounded-full bg-paper px-3 py-1 text-xs"><?= ($row['publication_version'] !== null ? ($row['status'] === 'ready' ? 'Validé' : 'Révision en cours') : 'Brouillon') ?></span></td></tr><?php endforeach; ?></tbody></table><?php if (!$rows): ?><p class="p-8 text-center text-sm text-ink/60">Aucune actualité ne correspond à votre recherche.</p><?php endif; ?></div>
<?php elseif ($page === 'edit'): require __DIR__ . '/editor.php'; ?>
<?php elseif ($page === 'history'): require __DIR__ . '/history.php'; ?>
<?php elseif ($page === 'media'): $media = query('SELECT * FROM media ORDER BY created_at DESC')->fetchAll(); ?>
    <section class="rounded-xl border border-line bg-ivory p-6"><h2 class="font-display text-2xl">Ajouter une image</h2><p class="mt-2 text-sm text-ink/60">JPG, PNG ou WebP · 8 Mo maximum par image.</p><form method="post" enctype="multipart/form-data" class="mt-5 grid items-end gap-5 tablet:grid-cols-2"><?= csrfField() ?><input type="hidden" name="action" value="upload"><div><?php field('Fichier image', 'image', '', 'file', 'required accept="image/jpeg,image/png,image/webp"'); ?></div><div><?php field('Description de l’image', 'alt', $_POST['alt'] ?? '', 'text', 'required maxlength="500"'); ?></div><button class="<?= $buttonClass ?> justify-self-start">Ajouter à la médiathèque</button></form></section>
    <?php if (!$media): ?><p class="mt-8 text-sm text-ink/60">Les nouvelles images apparaîtront ici. Les galeries déjà présentes sur le site restent disponibles dans leurs actualités.</p><?php endif; ?>
    <div class="mt-7 grid gap-5 tablet:grid-cols-2 wide:grid-cols-3"><?php foreach ($media as $row): ?><article class="overflow-hidden rounded-xl border border-line bg-ivory"><img src="<?= e(url('image', ['id' => $row['id']])) ?>" alt="<?= e($row['alt']) ?>" width="<?= (int) $row['width'] ?>" height="<?= (int) $row['height'] ?>" loading="lazy" class="aspect-[4/3] w-full object-cover"><div class="p-5"><p class="text-sm font-medium"><?= e($row['alt']) ?></p><p class="mt-2 text-xs text-ink/60"><?= (int) $row['width'] ?> × <?= (int) $row['height'] ?> · <?= round($row['bytes'] / 1024) ?> Ko</p><label class="mt-4 block text-xs text-ink/60" for="path-<?= e($row['id']) ?>">Chemin à copier dans une actualité</label><input id="path-<?= e($row['id']) ?>" class="<?= $inputClass ?>" readonly value="<?= e('/images/actualites/uploads/' . $row['filename']) ?>"></div></article><?php endforeach; ?></div>
<?php elseif ($page === 'users'): ?>
    <p class="mb-6 max-w-2xl text-sm leading-relaxed text-ink/65">Les rédacteurs préparent les brouillons et ajoutent des images. Les administrateurs valident les articles, préparent leur publication et gèrent les accès.</p>
    <div class="divide-y divide-line rounded-xl border border-line bg-ivory"><?php foreach (query('SELECT id,name,email,role,active FROM users ORDER BY name')->fetchAll() as $member): ?><div class="flex flex-wrap items-center justify-between gap-4 p-5"><div><p class="text-sm font-semibold"><?= e($member['name']) ?> <?= $member['active'] ? '' : '· Désactivé' ?></p><p class="mt-1 text-xs text-ink/60"><?= e($member['email']) ?> · <?= $member['role'] === 'admin' ? 'Administrateur' : 'Rédacteur' ?></p></div><?php if ($member['id'] !== $user['id']): ?><form method="post"><?= csrfField() ?><input type="hidden" name="action" value="toggle_user"><input type="hidden" name="id" value="<?= e($member['id']) ?>"><button class="<?= $secondaryClass ?>"><?= $member['active'] ? 'Désactiver l’accès' : 'Réactiver l’accès' ?></button></form><?php endif; ?></div><?php endforeach; ?></div>
    <section class="mt-8 rounded-xl border border-line bg-ivory p-6"><h2 class="font-display text-2xl">Créer un compte</h2><form method="post" class="mt-6 grid gap-5 tablet:grid-cols-2"><?= csrfField() ?><input type="hidden" name="action" value="create_user"><div><?php field('Nom', 'name', $_POST['name'] ?? '', 'text', 'required maxlength="100"'); ?></div><div><?php field('Adresse e-mail', 'email', $_POST['email'] ?? '', 'email', 'required maxlength="190"'); ?></div><div><?php field('Mot de passe initial', 'password', '', 'password', 'required minlength="12" maxlength="72" autocomplete="new-password"'); ?></div><div><label for="role" class="text-sm font-medium">Rôle</label><select id="role" name="role" class="<?= $inputClass ?>"><option value="editor">Rédacteur</option><option value="admin">Administrateur</option></select></div><p class="text-xs leading-relaxed text-ink/60 tablet:col-span-2">Remettez les identifiants à la personne concernée par votre canal habituel. Elle pourra changer son mot de passe dans « Mon compte ».</p><button class="<?= $buttonClass ?> justify-self-start">Créer le compte</button></form></section>
<?php elseif ($page === 'account'): ?>
    <section class="max-w-xl rounded-xl border border-line bg-ivory p-7"><h2 class="font-display text-2xl">Changer mon mot de passe</h2><p class="mt-3 text-sm text-ink/60">Vous devrez vous reconnecter après ce changement. Vos autres sessions seront également fermées.</p><form method="post" class="mt-6 space-y-5"><?= csrfField() ?><input type="hidden" name="action" value="change_password"><div><?php field('Mot de passe actuel', 'current_password', '', 'password', 'required autocomplete="current-password"'); ?></div><div><?php field('Nouveau mot de passe', 'password', '', 'password', 'required minlength="12" maxlength="72" autocomplete="new-password"'); ?></div><button class="<?= $buttonClass ?>">Changer le mot de passe</button></form></section>
<?php elseif ($page === 'publication'): ?>
    <section class="max-w-3xl rounded-xl border border-line bg-ivory p-7"><p class="text-xs font-semibold uppercase tracking-[.18em] text-accent">Préparation de la mise en ligne</p><h2 class="mt-3 font-display text-3xl">Les contenus validés, réunis.</h2><p class="mt-4 text-sm leading-relaxed text-ink/65">Cette étape rassemble la dernière version validée de chaque article et ses images. Les modifications en brouillon restent privées ; elles ne remplacent pas les versions validées.</p><p class="mt-4 rounded-lg bg-paper p-4 text-sm leading-relaxed">Le téléchargement ne modifie pas le site public. La personne chargée de sa mise en ligne doit encore construire et déployer cette publication.</p><form method="post" class="mt-6"><?= csrfField() ?><input type="hidden" name="action" value="export"><button class="<?= $buttonClass ?>">Télécharger les contenus validés</button></form></section>
    <section class="mt-8 max-w-3xl"><h2 class="mb-4 font-display text-2xl">Journal de l’équipe</h2><ol class="divide-y divide-line rounded-xl border border-line bg-ivory"><?php foreach (query('SELECT a.action,a.subject,a.created_at,u.name FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC,a.id DESC LIMIT 30')->fetchAll() as $event): ?><li class="p-5"><p class="text-sm"><strong><?= e($event['action']) ?></strong> · <?= e($event['subject']) ?></p><p class="mt-1 text-xs text-ink/60"><?= e($event['name'] ?? 'Installation') ?> · <?= e(str_replace(['T', 'Z'], [' ', ' UTC'], $event['created_at'])) ?></p></li><?php endforeach; ?></ol></section>
<?php else: ?><p>Cette page n’existe pas.</p><a href="/" class="mt-5 inline-block underline">Retour à l’accueil</a><?php endif; ?>
