<?php namespace Baruck;
function kpi(string $label, string $value, string $caption = '', ?int $delta = null, bool $upIsGood = true): void {
    global $cardClass;
    echo '<div class="' . $cardClass . ' p-6"><p class="text-sm text-ink/60">' . e($label) . '</p><p class="mt-3 font-display text-4xl">' . e($value) . '</p>';
    if ($delta !== null) {
        $good = ($delta >= 0) === $upIsGood;
        echo '<p class="mt-2 text-caption ' . ($delta === 0 ? 'text-ink/60' : ($good ? 'text-[#087a3e]' : 'text-[#b64820]')) . '">' . ($delta > 0 ? '+' : ($delta < 0 ? '−' : '')) . abs($delta) . ' % ' . e($caption) . '</p>';
    } elseif ($caption !== '') echo '<p class="mt-2 text-caption text-ink/60">' . e($caption) . '</p>';
    echo '</div>';
}
function adviceList(array $items, string $empty = ''): void {
    global $cardClass, $secondaryClass;
    if (!$items) { if ($empty !== '') echo '<p class="' . $cardClass . ' p-5 text-sm text-ink/70">' . e($empty) . '</p>'; return; }
    $marks = ['action' => ['bg-accent', 'À faire'], 'good' => ['bg-[#087a3e]', 'Bonne nouvelle'], 'info' => ['bg-gold', 'À savoir']];
    echo '<ul class="divide-y divide-line ' . $cardClass . '">';
    foreach ($items as $item) {
        echo '<li class="flex flex-wrap items-center justify-between gap-3 p-5"><p class="flex items-start gap-3 text-sm leading-relaxed"><span class="mt-1.5 inline-block size-2 shrink-0 rounded-full ' . $marks[$item['level']][0] . '" role="img" aria-label="' . $marks[$item['level']][1] . '"></span><span>' . e($item['text']) . '</span></p>';
        if ($item['page'] !== '' && $item['action'] !== '') echo '<a href="' . e(url($item['page'], $item['params'])) . '" class="' . $secondaryClass . ' px-4 py-2">' . e($item['action']) . '</a>';
        echo '</li>';
    }
    echo '</ul>';
}
?>
<?php if ($page === 'dashboard'): $today = gmdate('Y-m-d'); $audience = audienceSummary(30, $today); $editorial = editorialSummary($today); $advice = insights($audience, $editorial, $user['role'] === 'admin'); $todo = array_values(array_filter($advice, fn($item) => $item['level'] === 'action')); $notes = array_slice(array_values(array_filter($advice, fn($item) => $item['level'] !== 'action')), 0, 3); ?>
    <div class="mb-4 flex flex-wrap items-center justify-between gap-4"><h2 class="font-display text-2xl">À faire</h2><a href="<?= e(url('edit')) ?>" class="<?= $buttonClass ?>">Nouvelle actualité <span class="ml-4" aria-hidden="true">+</span></a></div>
    <?php adviceList($todo, 'Tout est à jour. Rien n’attend votre intervention.'); ?>
    <div class="mt-8 grid gap-4 tablet:grid-cols-2 wide:grid-cols-4">
        <?php if ($audience['active']): kpi('Visiteurs · 30 jours', (string) $audience['visitors'], 'vs 30 jours précédents', delta($audience['visitors'], $audience['previousVisitors'])); kpi('Pages vues · 30 jours', (string) $audience['views'], 'vs 30 jours précédents', delta($audience['views'], $audience['previousViews'])); else: kpi('Visiteurs · 30 jours', '—', 'Mesure d’audience non active'); kpi('Pages vues · 30 jours', '—', 'Mesure d’audience non active'); endif; ?>
        <?php kpi('Actualités validées', (string) $editorial['validated'], $editorial['unpublished'] + $editorial['revising'] > 0 ? ($editorial['unpublished'] + $editorial['revising']) . ' brouillon(s) en cours' : 'Aucun brouillon en attente'); ?>
        <?php kpi('Dernière actualité', $editorial['lastDate'] !== '' ? frenchDate($editorial['lastDate'], true) : '—', $editorial['daysSinceLast'] !== null ? 'il y a ' . $editorial['daysSinceLast'] . ' jour(s)' : 'Aucune actualité validée datée'); ?>
    </div>
    <div class="mt-8 grid gap-6 wide:grid-cols-[minmax(0,3fr)_minmax(0,2fr)]">
        <section class="<?= $cardClass ?> p-6"><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 class="font-display text-2xl">Visiteurs par jour</h2><a href="<?= e(url('stats')) ?>" class="text-sm underline underline-offset-4">Toutes les statistiques</a></div>
            <?php if ($audience['active']): echo barChart($audience['series'], 'visitors', 'visiteurs'); else: ?><p class="text-sm leading-relaxed text-ink/60">Les visites du site apparaîtront ici dès que la mesure d’audience sera activée sur le site public.</p><?php endif; ?>
        </section>
        <div class="space-y-6">
            <?php if ($notes): ?><section><h2 class="mb-4 font-display text-2xl">Bon à savoir</h2><?php adviceList($notes); ?></section><?php endif; ?>
            <section><div class="mb-4 flex items-center justify-between"><h2 class="font-display text-2xl">Dernières modifications</h2><a href="<?= e(url('articles')) ?>" class="text-sm underline underline-offset-4">Toutes les actualités</a></div><div class="divide-y divide-line <?= $cardClass ?>"><?php foreach (query('SELECT a.id,a.title,a.status,a.updated_at,p.version AS publication_version FROM articles a LEFT JOIN article_publications p ON p.article_id=a.id ORDER BY a.updated_at DESC,a.title LIMIT 5')->fetchAll() as $row): ?><a href="<?= e(url('edit', ['id' => $row['id']])) ?>" class="flex flex-wrap items-center justify-between gap-3 p-5 hover:bg-paper-deep/30"><span class="text-sm font-semibold"><?= e($row['title']) ?></span><span class="rounded-full bg-paper px-3 py-1 text-xs"><?= statusLabel($row) ?></span></a><?php endforeach; ?></div></section>
        </div>
    </div>
<?php elseif ($page === 'articles'): $search = is_string($_GET['q'] ?? null) ? substr($_GET['q'], 0, 120) : ''; $filter = in_array($_GET['status'] ?? '', ['draft', 'ready'], true) ? $_GET['status'] : ''; $rows = query('SELECT a.id,a.slug,a.title,a.category,a.article_date,a.status,a.updated_at,p.version AS publication_version FROM articles a LEFT JOIN article_publications p ON p.article_id=a.id WHERE a.title LIKE ? AND (? = ? OR a.status = ?) ORDER BY a.updated_at DESC,a.title', ['%' . $search . '%', $filter, '', $filter])->fetchAll(); $views = []; foreach (query("SELECT path, COUNT(*) AS views FROM page_views WHERE day >= ? AND path LIKE '/actualites/%/' GROUP BY path", [shiftDay(gmdate('Y-m-d'), -29)])->fetchAll() as $row) $views[$row['path']] = (int) $row['views']; ?>
    <div class="mb-6 flex flex-wrap items-center justify-between gap-4"><p class="text-sm text-ink/60"><?= count($rows) ?> actualité(s)</p><a href="<?= e(url('edit')) ?>" class="<?= $buttonClass ?>">Nouvelle actualité <span class="ml-4" aria-hidden="true">+</span></a></div>
    <form method="get" class="mb-6 grid items-end gap-4 tablet:grid-cols-[1fr_220px_auto]"><input type="hidden" name="page" value="articles"><div><?php field('Rechercher un titre', 'q', $search, 'search'); ?></div><div><label for="status" class="text-sm font-medium">Statut</label><select id="status" name="status" class="<?= $inputClass ?>"><option value="">Tous les statuts</option><option value="draft" <?= $filter === 'draft' ? 'selected' : '' ?>>Brouillons et révisions</option><option value="ready" <?= $filter === 'ready' ? 'selected' : '' ?>>Validés</option></select></div><button class="<?= $secondaryClass ?>">Filtrer</button></form>
    <div class="overflow-x-auto <?= $cardClass ?>"><table class="w-full text-left text-sm"><caption class="sr-only">Liste des actualités</caption><thead class="bg-paper-deep/35 text-xs text-ink/60"><tr><th scope="col" class="p-5">Titre</th><th scope="col" class="p-5">Catégorie</th><th scope="col" class="p-5">Date</th><th scope="col" class="p-5">Statut</th><?php if ($views): ?><th scope="col" class="p-5 text-right">Vues · 30 j</th><?php endif; ?></tr></thead><tbody class="divide-y divide-line"><?php foreach ($rows as $row): ?><tr><th scope="row" class="p-5 font-semibold"><a class="underline-offset-4 hover:underline" href="<?= e(url('edit', ['id' => $row['id']])) ?>"><?= e($row['title']) ?></a></th><td class="p-5"><?= e(categories()[$row['category']]) ?></td><td class="whitespace-nowrap p-5"><?= $row['article_date'] !== '' ? e(frenchDate($row['article_date'], true)) : 'À renseigner' ?></td><td class="p-5"><span class="whitespace-nowrap rounded-full bg-paper px-3 py-1 text-xs"><?= statusLabel($row) ?></span></td><?php if ($views): ?><td class="p-5 text-right tabular-nums"><?= (int) ($views['/actualites/' . $row['slug'] . '/'] ?? 0) ?></td><?php endif; ?></tr><?php endforeach; ?></tbody></table><?php if (!$rows): ?><p class="p-8 text-center text-sm text-ink/60">Aucune actualité ne correspond à votre recherche.</p><?php endif; ?></div>
<?php elseif ($page === 'boutique'):
    $search = is_string($_GET['q'] ?? null) ? substr($_GET['q'], 0, 120) : '';
    $rayon = array_key_exists($_GET['rayon'] ?? '', brandCategories()) ? $_GET['rayon'] : '';
    $rows = query('SELECT id,name,category,images,status,position FROM products WHERE name LIKE ? AND (? = ? OR category = ?) ORDER BY position,id', ['%' . $search . '%', $rayon, '', $rayon])->fetchAll();
    $catalog = array_column(mediaCatalog(), null, 'path');
    $online = count(array_filter($rows, fn($row) => $row['status'] === 'ready'));
    // Réordonner n’a de sens que sur la boutique entière : la liste filtrée saute des voisins.
    $sortable = $search === '' && $rayon === '';
?>
    <div class="mb-6 flex flex-wrap items-center justify-between gap-4"><p class="text-sm text-ink/60"><?= count($rows) ?> article(s) · <?= $online ?> en boutique</p><a href="<?= e(url('product')) ?>" class="<?= $buttonClass ?>">Ajouter un article <span class="ml-4" aria-hidden="true">+</span></a></div>
    <form method="get" class="mb-6 grid items-end gap-4 tablet:grid-cols-[1fr_220px_auto]"><input type="hidden" name="page" value="boutique"><div><?php field('Rechercher un article', 'q', $search, 'search'); ?></div><div><label for="rayon" class="text-sm font-medium">Rayon</label><select id="rayon" name="rayon" class="<?= $inputClass ?>"><option value="">Tous les rayons</option><?php foreach (brandCategories() as $key => $label): ?><option value="<?= e($key) ?>" <?= $rayon === $key ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><button class="<?= $secondaryClass ?>">Filtrer</button></form>
    <?php if (!$sortable): ?><p class="mb-4 text-caption text-ink/60">L’ordre d’affichage se modifie sur la liste complète, sans recherche ni filtre.</p><?php endif; ?>
    <div class="divide-y divide-line <?= $cardClass ?>">
        <?php foreach ($rows as $rank => $row): $photo = productImages($row)[0] ?? null; $thumb = $photo ? ($catalog[$photo['src']] ?? null) : null; ?>
        <div class="flex flex-wrap items-center gap-4 p-4">
            <img src="<?= e($thumb['preview'] ?? '') ?>" alt="" width="<?= (int) ($thumb['width'] ?? 1) ?>" height="<?= (int) ($thumb['height'] ?? 1) ?>" loading="lazy" class="size-16 shrink-0 rounded-lg bg-paper object-contain">
            <div class="min-w-0 grow"><a href="<?= e(url('product', ['id' => $row['id']])) ?>" class="text-sm font-semibold underline-offset-4 hover:underline"><?= e($row['name']) ?></a><p class="mt-1 text-xs text-ink/60"><?= e(brandCategories()[$row['category']] ?? $row['category']) ?> · <?= count(productImages($row)) ?> photo(s)</p></div>
            <span class="whitespace-nowrap rounded-full bg-paper px-3 py-1 text-xs"><?= $row['status'] === 'ready' ? 'En boutique' : 'Masqué' ?></span>
            <?php if ($sortable): ?>
            <div class="flex gap-2">
                <form method="post"><?= csrfField() ?><input type="hidden" name="action" value="move_product"><input type="hidden" name="id" value="<?= e($row['id']) ?>"><input type="hidden" name="direction" value="up"><button class="<?= $secondaryClass ?> px-3 py-2" <?= $rank === 0 ? 'disabled' : '' ?> aria-label="Monter <?= e($row['name']) ?>">↑</button></form>
                <form method="post"><?= csrfField() ?><input type="hidden" name="action" value="move_product"><input type="hidden" name="id" value="<?= e($row['id']) ?>"><input type="hidden" name="direction" value="down"><button class="<?= $secondaryClass ?> px-3 py-2" <?= $rank === count($rows) - 1 ? 'disabled' : '' ?> aria-label="Descendre <?= e($row['name']) ?>">↓</button></form>
            </div>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
        <?php if (!$rows): ?><p class="p-8 text-center text-sm text-ink/60"><?= $sortable ? 'La boutique est vide. Ajoutez un premier article pour ouvrir la collection.' : 'Aucun article ne correspond à votre recherche.' ?></p><?php endif; ?>
    </div>
<?php elseif ($page === 'product'): require __DIR__ . '/product.php'; ?>
<?php elseif ($page === 'coordonnees'): require __DIR__ . '/coordonnees.php'; ?>
<?php elseif ($page === 'edit'): require __DIR__ . '/editor.php'; ?>
<?php elseif ($page === 'history'): require __DIR__ . '/history.php'; ?>
<?php elseif ($page === 'stats'): require __DIR__ . '/statistics.php'; ?>
<?php elseif ($page === 'media'): $media = query('SELECT * FROM media ORDER BY created_at DESC')->fetchAll(); $usage = mediaUsage(); ?>
    <div class="mb-6 flex flex-wrap items-center justify-between gap-4"><p class="text-sm text-ink/60"><?= count($media) ?> image(s) importée(s)<?= count($media) ? ' · ' . round(array_sum(array_column($media, 'bytes')) / 1048576, 1) . ' Mo' : '' ?></p><button type="button" data-open="upload-dialog" class="<?= $buttonClass ?>">Ajouter une image <span class="ml-4" aria-hidden="true">+</span></button></div>
    <dialog id="upload-dialog" data-dialog <?= $error && ($_POST['action'] ?? '') === 'upload' ? 'data-open-on-load' : '' ?> aria-labelledby="upload-title" class="<?= $dialogClass ?>">
        <div class="flex items-center justify-between gap-4"><h2 id="upload-title" class="font-display text-title">Ajouter une image</h2><button type="button" data-close class="<?= $secondaryClass ?>">Fermer</button></div>
        <?php if ($error && ($_POST['action'] ?? '') === 'upload'): ?><p role="alert" class="mt-4 rounded-lg border border-[#b64820]/30 bg-[#b64820]/10 p-4 text-sm"><?= e($error) ?></p><?php endif; ?>
        <form method="post" enctype="multipart/form-data" class="mt-5 space-y-5"><?= csrfField() ?><input type="hidden" name="action" value="upload"><div><?php field('Fichier image', 'image', '', 'file', 'required accept="image/jpeg,image/png,image/webp"'); ?><p class="mt-2 text-caption text-ink/60">JPG, PNG ou WebP · 8 Mo maximum.</p></div><div><?php field('Description de l’image', 'alt', $_POST['alt'] ?? '', 'text', 'required maxlength="500"'); ?><p class="mt-2 text-caption text-ink/60">Décrivez ce que montre la photo pour les personnes qui ne peuvent pas la voir.</p></div><button class="<?= $buttonClass ?> w-full">Ajouter à la médiathèque</button></form>
    </dialog>
    <?php if (!$media): ?><p class="<?= $cardClass ?> p-8 text-center text-sm text-ink/60">Aucune image importée pour l’instant. Les photos déjà présentes sur le site restent disponibles dans les actualités.</p><?php endif; ?>
    <div class="grid gap-5 tablet:grid-cols-2 wide:grid-cols-3"><?php foreach ($media as $row): $used = $usage[$row['id']] ?? 0; ?><article class="overflow-hidden <?= $cardClass ?>"><img src="<?= e(url('image', ['id' => $row['id']])) ?>" alt="<?= e($row['alt']) ?>" width="<?= (int) $row['width'] ?>" height="<?= (int) $row['height'] ?>" loading="lazy" class="aspect-[4/3] w-full object-cover"><div class="p-5"><p class="text-sm font-medium"><?= e($row['alt']) ?></p><p class="mt-2 text-xs text-ink/60"><?= (int) $row['width'] ?> × <?= (int) $row['height'] ?> · <?= round($row['bytes'] / 1024) ?> Ko · <?= $used > 0 ? 'utilisée dans ' . $used . ' contenu' . ($used > 1 ? 's' : '') : 'non utilisée' ?></p><div class="mt-4 flex flex-wrap gap-3"><a href="<?= e(url('image', ['id' => $row['id'], 'download' => '1'])) ?>" class="<?= $secondaryClass ?> px-4 py-2">Télécharger</a><?php if ($used === 0 && $user['role'] === 'admin') confirmForm('delete_media', ['id' => $row['id']], 'Supprimer cette image ?', 'L’image « ' . $row['alt'] . ' » sera définitivement supprimée de la médiathèque.', 'Supprimer', $dangerClass . ' px-4 py-2'); ?></div></div></article><?php endforeach; ?></div>
<?php elseif ($page === 'users'): ?>
    <div class="mb-6 flex flex-wrap items-center justify-between gap-4"><p class="max-w-2xl text-sm leading-relaxed text-ink/65">Les rédacteurs préparent les brouillons et ajoutent des images. Les administrateurs valident, publient et gèrent les accès.</p><button type="button" data-open="user-dialog" class="<?= $buttonClass ?>">Créer un compte <span class="ml-4" aria-hidden="true">+</span></button></div>
    <div class="divide-y divide-line <?= $cardClass ?>"><?php foreach (query('SELECT id,name,email,role,active FROM users ORDER BY name')->fetchAll() as $member): ?><div class="flex flex-wrap items-center justify-between gap-4 p-5"><div><p class="text-sm font-semibold"><?= e($member['name']) ?> <?= $member['active'] ? '' : '· Désactivé' ?></p><p class="mt-1 text-xs text-ink/60"><?= e($member['email']) ?> · <?= $member['role'] === 'admin' ? 'Administrateur' : 'Rédacteur' ?></p></div><?php if ($member['id'] !== $user['id']) confirmForm('toggle_user', ['id' => $member['id']], $member['active'] ? 'Désactiver l’accès ?' : 'Réactiver l’accès ?', $member['active'] ? $member['name'] . ' ne pourra plus se connecter. Ses sessions ouvertes seront fermées.' : $member['name'] . ' pourra de nouveau se connecter avec son mot de passe.', $member['active'] ? 'Désactiver l’accès' : 'Réactiver l’accès', $member['active'] ? $dangerClass : $secondaryClass); ?></div><?php endforeach; ?></div>
    <dialog id="user-dialog" data-dialog <?= $error && ($_POST['action'] ?? '') === 'create_user' ? 'data-open-on-load' : '' ?> aria-labelledby="user-title" class="<?= $dialogClass ?>">
        <div class="flex items-center justify-between gap-4"><h2 id="user-title" class="font-display text-title">Créer un compte</h2><button type="button" data-close class="<?= $secondaryClass ?>">Fermer</button></div>
        <?php if ($error && ($_POST['action'] ?? '') === 'create_user'): ?><p role="alert" class="mt-4 rounded-lg border border-[#b64820]/30 bg-[#b64820]/10 p-4 text-sm"><?= e($error) ?></p><?php endif; ?>
        <form method="post" class="mt-5 space-y-5"><?= csrfField() ?><input type="hidden" name="action" value="create_user"><div><?php field('Nom', 'name', $_POST['name'] ?? '', 'text', 'required maxlength="100"'); ?></div><div><?php field('Adresse e-mail', 'email', $_POST['email'] ?? '', 'email', 'required maxlength="190"'); ?></div><div><?php field('Mot de passe initial', 'password', '', 'password', 'required minlength="12" maxlength="72" autocomplete="new-password"'); ?><p class="mt-2 text-caption text-ink/60">Au moins 12 caractères. La personne pourra le changer dans « Mon compte ».</p></div><div><label for="role" class="text-sm font-medium">Rôle</label><select id="role" name="role" class="<?= $inputClass ?>"><option value="editor" <?= ($_POST['role'] ?? '') === 'editor' ? 'selected' : '' ?>>Rédacteur</option><option value="admin" <?= ($_POST['role'] ?? '') === 'admin' ? 'selected' : '' ?>>Administrateur</option></select></div><button class="<?= $buttonClass ?> w-full">Créer le compte</button></form>
    </dialog>
<?php elseif ($page === 'account'): ?>
    <section class="max-w-xl <?= $cardClass ?> p-7"><h2 class="font-display text-2xl">Changer mon mot de passe</h2><p class="mt-3 text-sm text-ink/60">Vous devrez vous reconnecter après ce changement. Vos autres sessions seront également fermées.</p><form method="post" class="mt-6 space-y-5"><?= csrfField() ?><input type="hidden" name="action" value="change_password"><div><?php field('Mot de passe actuel', 'current_password', '', 'password', 'required autocomplete="current-password"'); ?></div><div><?php field('Nouveau mot de passe', 'password', '', 'password', 'required minlength="12" maxlength="72" autocomplete="new-password"'); ?></div><button class="<?= $buttonClass ?>">Changer le mot de passe</button></form></section>
<?php elseif ($page === 'publication'): $editorial = editorialSummary(gmdate('Y-m-d')); ?>
    <div class="grid gap-4 tablet:grid-cols-3"><?php kpi('Actualités validées', (string) $editorial['validated'], 'retenues pour la prochaine publication'); kpi('Nouvelles versions', (string) $editorial['pendingExport'], $editorial['lastExport'] === '' ? 'aucune publication préparée' : 'depuis la dernière préparation'); kpi('Dernière préparation', $editorial['lastExport'] !== '' ? frenchDate(substr($editorial['lastExport'], 0, 10), true) : '—', $editorial['withdrawnSinceExport'] > 0 ? $editorial['withdrawnSinceExport'] . ' retrait(s) depuis' : ''); ?></div>
    <section class="mt-6 max-w-3xl <?= $cardClass ?> p-7"><h2 class="font-display text-2xl">Préparer la mise en ligne</h2><p class="mt-3 text-sm leading-relaxed text-ink/65">Le fichier réunit la dernière version validée de chaque actualité et ses images. Les brouillons restent privés. Le téléchargement ne modifie pas le site : la mise en ligne reste une étape distincte.</p><form method="post" class="mt-6"><?= csrfField() ?><input type="hidden" name="action" value="export"><button class="<?= $buttonClass ?>">Télécharger les contenus validés</button></form></section>
    <section class="mt-8 max-w-3xl"><h2 class="mb-4 font-display text-2xl">Journal de l’équipe</h2><ol class="divide-y divide-line <?= $cardClass ?>"><?php foreach (query('SELECT a.action,a.subject,a.created_at,u.name FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC,a.id DESC LIMIT 30')->fetchAll() as $event): ?><li class="p-5"><p class="text-sm"><strong><?= e($event['action']) ?></strong> · <?= e($event['subject']) ?></p><p class="mt-1 text-xs text-ink/60"><?= e($event['name'] ?? 'Installation') ?> · <?= e(str_replace(['T', 'Z'], [' ', ' UTC'], $event['created_at'])) ?></p></li><?php endforeach; ?></ol></section>
<?php else: ?><p>Cette page n’existe pas.</p><a href="/" class="mt-5 inline-block underline">Retour à l’accueil</a><?php endif; ?>
